name: rebi_todo
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  get_it: ^7.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
flutter:
  uses-material-design: true


# Launcher icon configuration
flutter_launcher_icons:
  image_path: assets/icons/logo.png
  android: true
  web:
    generate: true
    image_path: assets/icons/logo.png

# Some versions of the tool expect this legacy key
flutter_icons:
  android: true
  image_path: assets/icons/logo.png
