// GENERATED BY HAND to avoid build_runner.
part of 'task_list_hive_model.dart';

class TaskListHiveModelAdapter extends TypeAdapter<TaskListHiveModel> {
  @override
  final int typeId = 2;

  @override
  TaskListHiveModel read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return TaskListHiveModel(
      id: fields[0] as String,
      name: fields[1] as String,
      createdAt: fields[2] as DateTime,
      order: fields[3] as int? ?? 0,
      iconCodePoint: fields[4] as int?,
    );
  }

  @override
  void write(BinaryWriter writer, TaskListHiveModel obj) {
    writer
      ..writeByte(5)
      ..writeByte(0)
      ..write(obj.id)
      ..writeByte(1)
      ..write(obj.name)
      ..writeByte(2)
      ..write(obj.createdAt)
      ..writeByte(3)
      ..write(obj.order)
      ..writeByte(4)
      ..write(obj.iconCodePoint);
  }
}
